Disabled WAN ping check by default (some VPN servers do not route ICMP)

diff --git a/jffs/usr/bin/checkcon b/jffs/usr/bin/checkcon
--- a/jffs/usr/bin/checkcon
+++ b/jffs/usr/bin/checkcon
@@ -2,7 +2,7 @@
 
 ########################################################################
 #                                                                      #
-#   WAN connection check v3.05                                         #
+#   WAN connection check v4.01                                         #
 #   (c) by Tobse (cthullu@protonmail.com) in 2017                      #
 #                                                                      #
 #   This script must be located on a USB stick, mounted on /jffs and   #
@@ -69,43 +69,49 @@ if [ "$VPNROUTE" == "" ]; then
     $VPNSCRIPT rnd
   fi
 else
+  echo -e "\033[1;32mVPN tunnel is up.\033[0m"
 
-  # repeatedly ping specified domain
-  printf "Pinging $PINGSERVER: "
-  PINGFAILS=0
-  CNT=0
-  while [ $CNT -lt $PINGTRIES ]
-  do
-    if ! ping -q -c 1 -W 1 $PINGSERVER >/dev/null; then
-      let "PINGFAILS++"
-      printf "-"
-    else
-      printf "+"
+  # check WAN connecting with pings
+  if [ "$CHECKWANWITHPINGS" == "yes" ]; then
+
+
+    # repeatedly ping specified domain
+    printf "Pinging $PINGSERVER: "
+    PINGFAILS=0
+    CNT=0
+    while [ $CNT -lt $PINGTRIES ]
+    do
+      if ! ping -q -c 1 -W 1 $PINGSERVER >/dev/null; then
+        let "PINGFAILS++"
+        printf "-"
+      else
+        printf "+"
+      fi
+      let "CNT++"
+    done
+
+    # ping results evaluation positive: exit
+    printf "\n"
+    echo $PINGFAILS of $PINGTRIES pings have failed.
+    if [ $PINGFAILS -lt $MAXFAILS ]; then
+      echo -e "\033[1;32mAll systems are functioning within normal parameters.\033[0m"
+      exit
     fi
-    let "CNT++"
-  done
 
-  # ping results evaluation positive: exit
-  printf "\n"
-  echo $PINGFAILS of $PINGTRIES pings have failed.
-  if [ $PINGFAILS -lt $MAXFAILS ]; then
-    echo -e "\033[1;32mAll systems are functioning within normal parameters.\033[0m"
-    exit
-  fi
+    # log ping fail
+    if [ "$LOGGING" == "yes" ]; then
+      NOWSTAMP=`date "+%Y-%m-%d %H:%M:%S"`
+      echo $NOWSTAMP $PINGFAILS/$PINGTRIES tries pinging $PINGSERVER failed >> $GENERALLOG
+    fi
 
-  # log ping fail
-  if [ "$LOGGING" == "yes" ]; then
-    NOWSTAMP=`date "+%Y-%m-%d %H:%M:%S"`
-    echo $NOWSTAMP $PINGFAILS/$PINGTRIES tries pinging $PINGSERVER failed >> $GENERALLOG
-  fi
-
-  # ping results evaluation negative: try to change VPN exit node
-  echo -e "\033[1;31mThere is probably no WAN connection.\033[0m"
-  if [ "$1" == "checkonly" ]; then
-    echo Taking no actions.
-    exit 0
-  else
-    echo Trying new VPN server anyway.
-    $VPNSCRIPT rnd
+    # ping results evaluation negative: try to change VPN exit node
+    echo -e "\033[1;31mThere is probably no WAN connection.\033[0m"
+    if [ "$1" == "checkonly" ]; then
+      echo Taking no actions.
+      exit 0
+    else
+      echo Trying new VPN server anyway.
+      $VPNSCRIPT rnd
+    fi
   fi
 fi
