New, polished and shiny version of VPN script which doesn't need server configuration files anymore, as it downloads the configurations by itself

diff --git a/jffs/usr/bin/vpn b/jffs/usr/bin/vpn
--- a/jffs/usr/bin/vpn
+++ b/jffs/usr/bin/vpn
@@ -2,17 +2,12 @@
 
 ########################################################################
 #                                                                      #
-#   VPN connector script v9.06                                         #
-#   (c) by Tobse (cthullu@protonmail.com) in 2017                      #
+#   VPN connector script v10.00                                        #
+#   (c) by Tobse (cthullu@protonmail.com) in 2022                      #
 #                                                                      #
 #   This script must be located on a USB stick, mounted on /jffs and   #
 #   expects the presence of the speed check script in /jffs/usr/bin/.  #
 #   All scripts must be "chmod ugo+x" in order to be executable.       #
-#   The script also expects the presence of the prepared VPN           #
-#   configuration files, sorted into directories at the defined        #
-#   config files directory, containing the files ca.crt,               #
-#   openvpn.conf and ta.key. See the files with these names at         #
-#   /tmp/openvpncl for the syntax.                                     #
 #                                                                      #
 ########################################################################
 
@@ -27,57 +22,8 @@ if [ -f "$DIRNAME/myconfig" ]; then
   source $DIRNAME/myconfig
 fi
 
-# log script call
-if [ "$LOGGING" == "yes" ]; then
-  NOWSTAMP=`date "+%Y-%m-%d %H:%M:%S"`
-  echo $NOWSTAMP vpn script called >> $GENERALLOG
-fi
-
-# create temporary directory if it doesn't exist yet
-if [ ! -d "$MYTMPDIR" ]; then
-  mkdir $MYTMPDIR
-fi
-
-# check file system for faulty flip to read-only mode
-echo Checking $JFFSPATH mount on write access.
-touch $MYTMPDIR/writetest.lock >/dev/null 2>/dev/null
-if [ -f "$MYTMPDIR/writetest.lock" ]; then
-  rm -f $MYTMPDIR/writetest.lock
-  echo -e "\033[1;32mWrite access to USB stick is given.\033[0m"
-else
-
-  # reboot if last reboot was more than ... seconds ago
-  BOOTDIFF=`expr $MINREBOOTPERIOD + 777`
-  if [ -f $LTRFILE ]; then
-    LASTBOOTED=`cat $LTRFILE`
-    BOOTDIFF=`expr $NOWSTAMP - $LASTBOOTED`
-  fi
-  if [ "$BOOTDIFF" -ge "$MINREBOOTPERIOD" ]; then
-    echo -e "\033[1;31mNo write access to USB stick. Reboot initiated.\033[0m"
-    sleep $REBOOTWAIT
-    if [ -f $LTRFILE ]; then
-      rm -f $LTRFILE
-    fi
-    echo $NOWSTAMP >> $LTRFILE
-    reboot
-  fi
-fi
-
-# check if country specified by parameter 1 is disallowed by configuation
-if [ ${#PARAM1} -ne 2 ] && [ "$1" != "" ]; then
-  EXCLUDECOUNTRIES=$(echo $IGNORECOUNTRIES | tr "," "\n")
-  INCLUDECOUNTRIES=$(echo $EXCLUSIVECOUNTRIES | tr "," "\n")
-  for i in $EXCLUDECOUNTRIES
-  do
-    if [ -z "${1##*$i*}" ]; then
-      echo The country \"$1\" is disallowed by configuration.
-      if [ -f $VPNLOCKFILE ]; then
-        rm -f $VPNLOCKFILE
-      fi
-      exit 1
-    fi
-  done
-fi
+SERVERSLISTFILE=$JFFSPATH/servers.list
+OVPNFILESURL=https://nordvpn.com/de/ovpn/
 
 # check if another instance of the vpn script is running already
 NOWSTAMP=`date "+%s"`
@@ -88,9 +34,9 @@ if [ -f $VPNLOCKFILE ]; then
     rm -f $VPNLOCKFILE
   else
     echo -e "\033[1;31mAnother instance of the vpn script is running since $RUNNINGSINCE seconds.\033[0m"
-    echo -e "\033[1;31mUse killvpn command to kill this instance and retry after that or simply wait.\033[0m"
     MUSTWAIT=`expr $MAXVPNEXECTIME - $RUNNINGSINCE`
     echo "You can restart this script in $MUSTWAIT seconds."
+    echo -e "\033[1;31mUse the killvpn command to kill this instance and retry after that or simply wait the $MUSTWAIT seconds.\033[0m"
     exit 1
   fi
 fi
@@ -101,6 +47,22 @@ CURLSUPPORTED=yes
 RESULT=`command -v curl`
 if [ "$RESULT" == "" ]; then
   CURLSUPPORTED=no
+fi
+
+# check if country specified by parameter 1 is disallowed by configuation
+EXCLUDECOUNTRIES=$(echo $IGNORECOUNTRIES | tr "," "\n")
+INCLUDECOUNTRIES=$(echo $EXCLUSIVECOUNTRIES | tr "," "\n")
+if [ ${#1} -eq 2 ]; then
+  for i in $EXCLUDECOUNTRIES
+  do
+    if [ -z "${1##*$i*}" ]; then
+      echo -e "\033[1;31mThe country \"$1\" is disallowed by configuration.\033[0m"
+      if [ -f $VPNLOCKFILE ]; then
+        rm -f $VPNLOCKFILE
+      fi
+      exit 1
+    fi
+  done
 fi
 
 # count amount of URLs for IP address lookup from config
@@ -119,90 +81,132 @@ for IPADDRESSURL in $IPADDRESSURLS ; do
   let CNT=$CNT+1
   if [ $CNT -eq $RND ]; then
     IPADDRESSURL=http://$IPADDRESSURL
-    MYIP=`wget -t 3 -T 10 -q -O - $IPADDRESSURL`
-    if [ $? -eq 0 ]; then
+    OLDIP=`wget -t 3 -T 10 -q -O - $IPADDRESSURL`
+    if [ $? -eq 0 ] || [ $CNT -gt $RND ]; then
       break
     fi
+    echo -e "\033[1;31mIP address lookup failed.\033[0m"
   fi
 done
 echo "Public IP address lookup will be done via $IPADDRESSURL."
 
+# update the NordVPN servers file if it is outdated
+if [[ ! -f "$SERVERSLISTFILE" ]] || [[ $(find "$SERVERSLISTFILE" -mtime +1 -print) ]]; then
+
+  # download OVPN files list from NordVPN
+  if [ "$CURLSUPPORTED" == "yes" ]; then
+    OVPNHTML=$(curl --connect-timeout 3 -ks $OVPNFILESURL)
+  else
+    OVPNHTML=`wget -t 3 -T 10 -q -O - $OVPNFILESURL`
+  fi
+
+  # parse OVPN list with PHP and write servers to file
+  PHP=`echo $SERVERSLISTFILE@@@@@$OVPNHTML|php -nr '
+    $params = explode("@@@@@", fgets(STDIN));
+    $servers = array();
+    preg_match_all("%href=\"([^\"]+?\.ovpn)%sim", $params[1], $urls);
+    foreach ($urls[1] as $url) {
+      preg_match("%/([^/\.]+?)\.nordvpn%", $url, $server);
+      $servers[] = $server[1];
+    }
+    file_put_contents(trim($params[0]), implode("\n", $servers));
+  '`
+
+fi
+
+# read servers from file
+sort $SERVERSLISTFILE | uniq > $MYTMPDIR/servers.list
+mv $MYTMPDIR/servers.list $SERVERSLISTFILE
+SERVERS=`cat $SERVERSLISTFILE`
+AMTSERVERS=0
+for SERVER in $SERVERS ; do
+  let AMTSERVERS=$AMTSERVERS+1
+done
+echo -e "\033[1;32mGot $AMTSERVERS potential servers to connect to.\033[0m"
+
 # get command line parameter
-PARAM1="$1"
+PARAM1=`echo "$1" | awk '{print tolower($0)}'`
 
 # check for empty parameter 1
 if [ "$PARAM1" == "" ]; then
-  echo -e "\033[1;31mNo parameter given.\033[0m"
-  echo Please use a server directory as parameter from the following list:
-  ls $CONFIGFILESDIR
+  echo -e "\033[1;31mNo parameter was given.\033[0m"
+  echo Please use a two letter country shortcut or
+  echo -e "a server as parameter from the following \033[1;37m$AMTSERVERS\033[0m items list:"
+  echo
+  CNT=0
+  for SERVER in $SERVERS ; do
+    echo -en "$SERVER\t"
+    let CNT=$CNT+1
+    if [ `expr $CNT % 10` -eq 0 ]; then
+      echo
+    fi
+    if [ `expr $CNT % 150` -eq 0 ]; then
+      read -n 1 -s
+    fi
+  done
+  echo
+  echo
   echo If you\'re not sure which one to pick, just use \"rnd\" or the two letters describing a country to pick a random server
-  if [ -f $VPNLOCKFILE ]; then
-    rm -f $VPNLOCKFILE
-  fi
   exit 1
 fi
 
-# check for wrong parameter 1
-if [ "$PARAM1" != "rnd" ] && [ ${#PARAM1} -ne 2 ]; then
-  if [ ! -d "$CONFIGFILESDIR/$PARAM1/" ]; then
-    echo -e "\033[1;31mDirectory $CONFIGFILESDIR/$PARAM1/ doesn't exist.\033[0m"
+# filter servers by country if EXCLUSIVECOUNTRIES are specified
+if [ "$EXCLUSIVECOUNTRIES" != "" ]; then
+  touch $MYTMPDIR/servers.tmp
+  touch $MYTMPDIR/exservers.tmp
+  for i in $INCLUDECOUNTRIES
+  do
+    EXSERVERS=`cat $SERVERSLISTFILE | grep -e "$i\d"`
+    rm -f $MYTMPDIR/exservers.tmp
+    for i in $EXSERVERS
+    do
+      echo $i >> $MYTMPDIR/exservers.tmp
+    done
+    cat $MYTMPDIR/exservers.tmp >> $MYTMPDIR/servers.tmp
+  done
+  SERVERS=`cat $MYTMPDIR/servers.tmp`
+  AMTSERVERS=`echo $SERVERS | wc -w`
+  echo -e "\033[1;37mConfiguration\033[0m narrowed down server list to \033[1;37m$AMTSERVERS\033[0m potential connection candidates."
+  if [ $AMTSERVERS -lt 1 ]; then
     if [ -f $VPNLOCKFILE ]; then
       rm -f $VPNLOCKFILE
     fi
     exit 1
   fi
+else
+  SERVER=$1
 fi
 
-# kill all speedcheck scripts
-killall -q speedcheck >/dev/null 2>/dev/null
-
-# delete start time file
-if [ -f $STSFILE ]; then
-  rm -f $STSFILE
-fi
-
-# read local servers list outside of loop
-if [ "$1" == "rnd" ] || [ ${#1} -eq 2 ]; then
-  echo -n Reading locally stored servers list...
-  SERVERDIRS=`find $CONFIGFILESDIR/ -type d`
-  AMTSERVERS=0
-  for SERVERDIR in $SERVERDIRS ; do
-    let AMTSERVERS=$AMTSERVERS+1
-  done
-  echo
-  echo -e "\033[1;32mGot $AMTSERVERS potential servers to connect to.\033[0m"
-
-  # filter servers by country if two characters were stated
-  if [ ${#1} -eq 2 ]; then
-    NEWSERVERDIRS=""
-    let CMPSTR=${#CONFIGFILESDIR}+2
-    let CMPEND=$CMPSTR+1
-    for SERVERDIR in $SERVERDIRS ; do
-      SERVERCOUNTRY=$(echo $SERVERDIR | cut -c${CMPSTR}-${CMPEND})
-      if [ "$SERVERCOUNTRY" == "$1" ]; then
-        NEWSERVERDIRS=$NEWSERVERDIRS$SERVERDIR" "
-      fi
-    done
-    SERVERDIRS=$NEWSERVERDIRS
-    AMTSERVERS=0
-    for SERVERDIR in $SERVERDIRS ; do
-      let AMTSERVERS=$AMTSERVERS+1
-    done
-    echo Server list narrowed down by paramter \"$1\" to $AMTSERVERS potential connection candidates.
-    if [ $AMTSERVERS -lt 1 ]; then
-      if [ -f $VPNLOCKFILE ]; then
-        rm -f $VPNLOCKFILE
-      fi
-      exit 1
-    fi
+# filter servers by country if two characters were stated
+if [ ${#1} -eq 2 ]; then
+  if [ "$EXCLUSIVECOUNTRIES" != "" ]; then
+    SERVERS=`cat $MYTMPDIR/servers.tmp | grep -e "$1\d"`
+  else
+    SERVERS=`cat $SERVERSLISTFILE | grep -e '$1\d'`
   fi
+  AMTSERVERS=`echo $SERVERS | wc -w`
+  echo -e "\033[1;37mParameter \"$1\"\033[0m narrowed down server list to \033[1;37m$AMTSERVERS\033[0m potential connection candidates."
+  if [ $AMTSERVERS -lt 1 ]; then
+    if [ -f $VPNLOCKFILE ]; then
+      rm -f $VPNLOCKFILE
+    fi
+    echo -e "\033[1;31mThese aren't the servers you are looking for.\033[0m"
+    exit 1
+  fi
+else
+  SERVER=$1
 fi
 
+# remove temporary files
+rm -f $MYTMPDIR/servers.tmp
+rm -f $MYTMPDIR/exservers.tmp
+
+# download server loads if specified by config
 if [ "$CHECKMAXLOAD" == "yes" ]; then
 
   # read NordVPN servers list (realtime data)
   SERVERSJSON=
-  echo -n Updating list with load percentages...
+  echo -n Retrieving server load percentages...
   if [ "$CURLSUPPORTED" == "yes" ]; then
     SERVERSJSON=$(curl --connect-timeout 3 -ks $SERVERLISTURL)
   else
@@ -211,19 +215,11 @@ if [ "$CHECKMAXLOAD" == "yes" ]; then
 fi
 echo
 
-# recount amount of server config directories
-AMT=0
-for SERVERDIR in $SERVERDIRS ; do
-  if [ "$SERVERDIR" != "$CONFIGFILESDIR/" ]; then
-    let AMT=$AMT+1
-  fi
-done
-
 RETRIESDONE=0
 while [[ $RETRIESDONE -lt $MAXTRIES ]]; do
 
   # if parameter 1 is "rnd" user wants a random server
-  # read server configuration directories
+  # read server configurations
   if [ "$1" == "rnd" ] || [ ${#1} -eq 2 ]; then
 
     # loop as long as server is in excluded countries list
@@ -239,28 +235,19 @@ while [[ $RETRIESDONE -lt $MAXTRIES ]]; do
       LOADISOKAY=yes
 
       # generate random number
-      # between 1 and amount of server directories
-      RND=`awk -v min=1 -v max=$AMT 'BEGIN{srand(); print int(min+rand()*(max-min+1))}'`
+      # between 1 and amount of server configurations
+      RND=`awk -v min=1 -v max=$AMTSERVERS 'BEGIN{srand(); print int(min+rand()*(max-min+1))}'`
 
       # now pick $RND from list
       CNT=0
-      for SERVERDIR in $SERVERDIRS ; do
-        if [ "$SERVERDIR" != "$CONFIGFILESDIR/" ]; then
-          let CNT=$CNT+1
-        fi
+      for SERVER in $SERVERS ; do
+        let CNT=$CNT+1
         if [ $CNT -eq $RND ]; then
-          SERVER=`echo $SERVERDIR | sed "s|$CONFIGFILESDIR/||g"`
           PARAM1=$SERVER
+          break
         fi
       done
-
-      # check if selected server matches force protocol config
-      if [ "$FORCEPROTOCOL" != "" ]; then
-        WRONGPROTOCOL=yes
-        if [ -z "${PARAM1##*$FORCEPROTOCOL*}" ]; then
-          WRONGPROTOCOL=no
-        fi
-      fi
+      sleep 1
 
       # check if selected server is in a to be excluded country
       if [ "$WRONGPROTOCOL" == "no" ]; then
@@ -274,7 +261,7 @@ while [[ $RETRIESDONE -lt $MAXTRIES ]]; do
 
         # check if selected server is in an exclusive country
         if [ "$WRONGCOUNTRY" == "no" ]; then
-          if [ "$EXCLUSIVECOUNTRIES" != "" ]; then
+          if [ "$1" == "rnd" ] && [ "$EXCLUSIVECOUNTRIES" != "" ]; then
             CORRECTCOUNTRY=no
             for i in $INCLUDECOUNTRIES
             do
@@ -350,15 +337,20 @@ while [[ $RETRIESDONE -lt $MAXTRIES ]]; do
   let TRYNUMBER=$RETRIESDONE+1
   echo
   echo -e "\033[1;37mThis is try #$TRYNUMBER of $MAXTRIES."
-  echo -e "Connecting to server $PARAM1.\033[0m"
+  echo -e "Connecting to server \033[1;37m$PARAM1\033[0m.\033[0m"
   echo
-  OLDIP=`wget -t 3 -T 10 -q -O - $IPADDRESSURL`
+  while : ; do
+    OLDIP=`wget -t 3 -T 10 -q -O - $IPADDRESSURL`
+    if [ $? -eq 0 ]; then
+      break
+    fi
+  done
   NEWIP=$OLDIP
 
   # check if we're connected to the VPN
   VPNROUTE=`route -n | grep $VPNINTERFACE`
   if [ "$VPNROUTE" == "" ]; then
-    echo -e "\033[33mWe're not connected to the VPN.\033[0m"
+    echo -e "\033[33mWe're not connected to the VPN yet.\033[0m"
   else
 
     # display current public IPv4
@@ -381,6 +373,11 @@ while [[ $RETRIESDONE -lt $MAXTRIES ]]; do
       VPNROUTE=`route -n | grep $VPNINTERFACE`
       if [ "$VPNROUTE" == "" ]; then
         NEWIP=`wget -t 3 -T 10 -q -O - $IPADDRESSURL`
+        if [ $? -ne 0 ]; then
+          echo
+          echo -e "\033[1;31mIP address lookup failed.\033[0m"
+        fi
+        break
       fi
     done
     echo
@@ -393,15 +390,35 @@ while [[ $RETRIESDONE -lt $MAXTRIES ]]; do
     echo Current public IPv4 is $NEWIP
   fi
 
-  # copy given server files and restart the VPN
-  cp $CONFIGFILESDIR/$PARAM1/* /tmp/openvpncl/
+  # download server configuration and restart VPN
+  echo "Downloading configuration for server $SERVER."
+  PROTOCOL=tcp
+  PORT=443
+  if [ "$2" != "" ]; then
+    PROTOCOL=`echo "$2" | awk '{print tolower($0)}'`
+  fi
+  if [ "$FORCEPROTOCOL" != "" ]; then
+    PROTOCOL=$FORCEPROTOCOL
+  fi
+  if [ "$PROTOCOL" == "udp" ]; then
+    PORT=1194
+  fi
+  OVPNURL=https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/$PARAM1.nordvpn.com.$PROTOCOL$PORT.ovpn
   chmod og-r /tmp/openvpncl/*
+  if [ "$CURLSUPPORTED" == "yes" ]; then
+    curl -kso /tmp/openvpncl/openvpn.conf $OVPNURL
+  else
+    wget -q $OVPNURL -P /tmp/openvpncl -O openvpn.conf
+  fi
+  echo "Connecting to server $PARAM1 with $PROTOCOL at port $PORT."
+  killall -q openvpn
+  sleep 1
   OPENVPNLOG_OLD=
   LASTLOGLINE=
   if [ -f $VPNLOG ]; then
     LASTLOGLINE=`tail -n1 $VPNLOG`
   fi
-  openvpn --config /tmp/openvpncl/openvpn.conf --route-up /tmp/openvpncl/route-up.sh --log $VPNLOG --daemon --auth-nocache --script-security 2
+  openvpn --config /tmp/openvpncl/openvpn.conf --auth-user-pass /tmp/openvpncl/credentials --route-up /tmp/openvpncl/route-up.sh --log $VPNLOG --daemon --auth-nocache --data-ciphers-fallback 'AES-256-CBC' --script-security 2 --dev $VPNINTERFACE
 
   # wait for new IPv4
   OLDIP=$NEWIP
@@ -464,6 +481,9 @@ while [[ $RETRIESDONE -lt $MAXTRIES ]]; do
         startservice dnsmasq
         sleep 5
         NEWIP=`wget -t 5 -T 10 -q -O - $IPADDRESSURL`
+        if [ $? -ne 0 ]; then
+          echo -e "\033[1;31mIP address lookup failed.\033[0m"
+        fi
       fi
     fi
     NOW=`date +%s`
@@ -472,7 +492,7 @@ while [[ $RETRIESDONE -lt $MAXTRIES ]]; do
 
   # echo new IPv4, city and country
   if [ "$NEWIP" == "$OLDIP" ]; then
-    echo -e "\033[1;31mIPv4 hasn't changed.\033[0m"
+    echo -e "\033[1;31mIPv4 hasn't changed ($OLDIP).\033[0m"
     VPNROUTE=`route -n | grep $VPNINTERFACE`
     if [ "$VPNROUTE" == "" ]; then
 
